#!/usr/bin/env bash
# Generate .contractmesh/generated/workspace-health.md from contractmesh.yml and local git state.
# Table columns may later include Known gaps / Known gaps count (see blockquote in output).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$WORKSPACE_DIR/.contractmesh/generated"
OUT_MD="$OUT_DIR/workspace-health.md"

REPOS=()
while IFS= read -r repo || [[ -n "$repo" ]]; do
  [[ -z "$repo" ]] && continue
  REPOS+=("$repo")
done < <(python3 -m contractmesh.engine.workspace_manifest repos-lines "$WORKSPACE_DIR")

mkdir -p "$OUT_DIR"

{
  echo "# Workspace health"
  echo ""
  echo "Generated by \`scripts/gen-workspace-health.sh\` — do not edit by hand."
  echo ""
  echo "> Evolução futura: coluna **Known gaps** ou **Known gaps count** por repositório para visão imediata de risco — ainda não incluída nesta versão."
  echo ""
  echo "| Repository | Clonado | Branch | Dirty | AGENTS.md | contracts README |"
  echo "|------------|---------|--------|-------|-----------|-------------------|"
} >"$OUT_MD"

for repo in "${REPOS[@]}"; do
  rp="$WORKSPACE_DIR/$repo"
  cloned=não
  branch="-"
  dirty=não
  agents=-
  contracts=-

  if [[ -d "$rp/.git" ]]; then
    cloned=sim
    branch=$(git -C "$rp" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "?")
    if [[ -n "$(git -C "$rp" status --porcelain 2>/dev/null)" ]]; then
      dirty=sim
    fi
    [[ -f "$rp/AGENTS.md" ]] && agents=ok || agents=falta
    [[ -f "$rp/docs/ai/contracts/README.md" ]] && contracts=ok || contracts=falta
  fi

  echo "| **$repo** | $cloned | $branch | $dirty | $agents | $contracts |" >>"$OUT_MD"
done

echo "Wrote $OUT_MD"
